apiVersion: v1
kind: Service
metadata:
  name: inspect-server
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 30000
  selector:
    app: inspect-server
  type: NodePort
